config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :tweets, only: [:new, :create, :destroy, :edit, :update, :show] do
    resources :comments, only: [:create]
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :tweets
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.create(comment_params)
    redirect_to tweet_path
  end
  
  private
  def comment_params
    params.permit(:text, :tweet_id).merge(user_id: current_user.id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  
  def index
    @tweets = Tweet.includes(:user).all.order("created_at DESC").page(params[:page]).per(3)
  end
  
  def new
  end
  
  def create
    @tweet = Tweet.create(tweet_params)
  end
  
  def destory
    @tweet = Tweet.find(params[:id])
    if current_user.id == @tweet.user_id
      @tweet.destory
    end
  end
  
  def edit
    @tweet = Tweet.find(params[:id])
  end
  
  def update
    @tweet = Tweet.find(params[:id])
    if current_user.id == @tweet.user_id
      @tweet.update(tweet_params)
    end
  end
  
  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.includes(:user)
  end
  
  private
  def tweet_params
    params.permit(:text, :image, :detail).merge(user_id: current_user.id)
  end
  
  def move_to_index
    unless user_signed_in?
      redirect_to :root
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @tweets = current_user.tweets.page(params[:page]).per(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepuySynthes PRODUCT</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>
  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/"><span>Depuy</span>Synthes PRODUCT</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.nickname %>
              <ul class="user__info">
                <li>
                  <%= link_to "マイページ", user_path(current_user.id), method: :get %>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </span>
            <%= link_to "製品登録", new_tweet_path, method: :get, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "新規登録", new_user_registration_path, method: :get, class: "post" %>
            <%= link_to "ログイン", new_user_session_path, method: :get, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <div style="background-image: url("product/app/assets/images/back_image.jpg");">
      <%= yield %>
    </div>
    <footer>
      <p>
        Copyright DepuySynthes PRODUCT 2020.
      </p>
    </footer>
  </body>
</html>

app/views/tweets/_tweet_html.erb
<div class="content_post" style="background-image: url(<%= tweet.image %>);">
      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <div class="more">
          <span><%= image_tag "arrow_top.png" %></span>
          <ul class="more_list">
            <li>
              <%= link_to "詳細", tweet_path(tweet.id), method: :get %>
            </li>
            <li>
              <%= link_to "編集", edit_tweet_path(tweet.id), method: :get %>
            </li>
            <li>
              <%= link_to "削除", tweet_path(tweet.id), method: :delete %>
            </li>
          </ul>
        </div>
      <% end %>
      <%= simple_format(tweet.text) %>
      <span class="name">
        <a herf="/users/<%= tweet.user_id %>"><span>登録者</span><%= tweet.user.nickname %></a>
      </span>
    </div>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>登録が完了しました</h3>
    <%= link_to "製品一覧へ戻る", root_path, method: :get, class: "btn" %>
  </div>
</div>

app/views/tweets/destory.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました</h3>
    <%= link_to "製品一覧へ戻る", root_path, method: :get %>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="contents row">
  <% form_tag("/tweets/#{@tweet.id}", method: :patch) do %>
    <h3>
      編集する
    </h3>
    <input type="text", name="image", value="<%= @tweet.image %>", placeholder="Image Url", autofocus="true">
    <textarea name="text", placeholder="Product Name", rows="10", cols="30"><%= @tweet.text %></textarea>
    <textarea name="text", placeholder="Product Summary", rows="10", cols="50"><%= @tweet.detail %></textarea>
    <input type="submit", value="SEND">
  <% end %>
</div>

app/views/tweets/index.html.erb
<div class="contents row">
  <% @tweets.each do |tweet| %>
   <div class="content_post" style="background-image: url(<%= tweet.image %>);">
      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <div class="more">
          <span><%= image_tag "arrow_top.png" %></span>
          <ul class="more_list">
            <li>
              <%= link_to "詳細", tweet_path(tweet.id), method: :get %>
            </li>
            <li>
              <%= link_to "編集", edit_tweet_path(tweet.id), method: :get %>
            </li>
            <li>
              <%= link_to "削除", tweet_path(tweet.id), method: :delete %>
            </li>
          </ul>
        </div>
      <% end %>
      <%= simple_format(tweet.text) %>
      <span class="name">
        <a herf="/users/<%= tweet.user_id %>"><span>登録者</span><%= tweet.user.nickname %></a>
      </span>
    </div>
  <% end %>
  <%= paginate(@tweets) %>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <%= form_tag('/tweets', method: :post) do %>
    <h3>
      登録する
    </h3>
    <input type="text", name="image", placeholder="Image Url">
    <textarea name="text", placeholder="Product Name", rows="10", cols="30"></textarea>
    <textarea name="detail", placeholder="Product Summary", rows="10", cols="50"></textarea>
    <input type="submit", value="Register">
  <% end %>
</div>

app/views/tweets/show.html.erb
<div class="contents row">
    <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
      <% if user_signed_in? && current_user.id == @tweet.user_id %>
        <div class="more">
          <span><%= image_tag "arrow_top.png" %></span>
          <ul class="more_list">
            <li>
              <%= link_to "編集", edit_tweet_path(@tweet.id), method: :get %>
            </li>
            <li>
              <%= link_to "削除", tweet_path(@tweet.id), method: :delete %>
            </li>
          </ul>
        </div>
      <% end %>
      <%= simple_format(@tweet.text) %>
      <span class="name">
        <a herf="/users/<%= @tweet.user_id %>"><span>登録者</span><%= @tweet.user.nickname %></a>
      </span>
    </div>
    
    <div class="container">
      <h3>【Product Summary】</h3>
        <%= simple_format(@tweet.detail) %>
    </div>
    
    <div class="comments">
      <h3>【comment一覧】</h3>
        <% @comments.each do |comment| %>
          <p>
            <strong><a href="user/comment.user_id"><%= comment.user.nickname %></a></strong>
            <%= simple_format(comment.text) %>
          </p>
        <% end %>
    </div>
    
    <div class="container"> 
    <% if current_user %>
      <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post) do %>
        <textarea name="text" placeholder="コメント" rows="2" cols="30"></textarea>
        <input type="submit" value="COMMENT">
      <% end %>
    <% end %>
    </div>
</div>

app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました</h3>
    <%= link_to "製品一覧へ戻る", root_path, method: :get %>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
  <% @tweets.each do |tweet| %>
    <div class="content_post" style="background-image: url(<%= tweet.image %>);">
      <%= simple_format(tweet.text) %>
    </div>
  <% end %>
  <%= paginate(@tweets) %>
</div>